development: &default
  adapter: mysql2
  database: iBeaconCMS_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: iBeaconCMS_test

production:
  adapter: mysql2
  database: iBeaconCMS_production
  encoding: utf8
  min_messages: warning
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>