require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DetectionsController do

  # This should return the minimal set of attributes required to create a valid
  # Detection. As you add validations to Detection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.build(:detection).attributes }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DetectionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all detections as @detections" do
      detection = Detection.create! valid_attributes
      get :index, {}, valid_session
      assigns(:detections).should eq([detection])
    end
  end

  describe "GET show" do
    it "assigns the requested detection as @detection" do
      detection = Detection.create! valid_attributes
      get :show, {:id => detection.to_param}, valid_session
      assigns(:detection).should eq(detection)
    end
  end

  describe "GET new" do
    it "assigns a new detection as @detection" do
      get :new, {}, valid_session
      assigns(:detection).should be_a_new(Detection)
    end
  end

  describe "GET edit" do
    it "assigns the requested detection as @detection" do
      detection = Detection.create! valid_attributes
      get :edit, {:id => detection.to_param}, valid_session
      assigns(:detection).should eq(detection)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Detection" do
        expect {
          post :create, {:detection => valid_attributes}, valid_session
        }.to change(Detection, :count).by(1)
      end

      it "assigns a newly created detection as @detection" do
        post :create, {:detection => valid_attributes}, valid_session
        assigns(:detection).should be_a(Detection)
        assigns(:detection).should be_persisted
      end

      it "redirects to the created detection" do
        post :create, {:detection => valid_attributes}, valid_session
        response.should redirect_to(Detection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved detection as @detection" do
        # Trigger the behavior that occurs when invalid params are submitted
        Detection.any_instance.stub(:save).and_return(false)
        post :create, {:detection => { "beacon" => "invalid value" }}, valid_session
        assigns(:detection).should be_a_new(Detection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Detection.any_instance.stub(:save).and_return(false)
        post :create, {:detection => { "beacon" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested detection" do
        detection = Detection.create! valid_attributes
        # Assuming there are no other detections in the database, this
        # specifies that the Detection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Detection.any_instance.should_receive(:update).with({ :beacon_id => 2 })
        put :update, {:id => detection.to_param, :detection => { :beacon_id => 2 }}, valid_session
      end

      it "assigns the requested detection as @detection" do
        detection = Detection.create! valid_attributes
        put :update, {:id => detection.to_param, :detection => valid_attributes}, valid_session
        assigns(:detection).should eq(detection)
      end

      it "redirects to the detection" do
        detection = Detection.create! valid_attributes
        put :update, {:id => detection.to_param, :detection => valid_attributes}, valid_session
        response.should redirect_to(detection)
      end
    end

    describe "with invalid params" do
      it "assigns the detection as @detection" do
        detection = Detection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Detection.any_instance.stub(:save).and_return(false)
        put :update, {:id => detection.to_param, :detection => { "beacon" => "invalid value" }}, valid_session
        assigns(:detection).should eq(detection)
      end

      it "re-renders the 'edit' template" do
        detection = Detection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Detection.any_instance.stub(:save).and_return(false)
        put :update, {:id => detection.to_param, :detection => { "beacon" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested detection" do
      detection = Detection.create! valid_attributes
      expect {
        delete :destroy, {:id => detection.to_param}, valid_session
      }.to change(Detection, :count).by(-1)
    end

    it "redirects to the detections list" do
      detection = Detection.create! valid_attributes
      delete :destroy, {:id => detection.to_param}, valid_session
      response.should redirect_to(detections_url)
    end
  end

end
