require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TemplateWinesController do

  # This should return the minimal set of attributes required to create a valid
  # TemplateWine. As you add validations to TemplateWine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TemplateWinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all template_wines as @template_wines" do
      template_wine = TemplateWine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:template_wines).should eq([template_wine])
    end
  end

  describe "GET show" do
    it "assigns the requested template_wine as @template_wine" do
      template_wine = TemplateWine.create! valid_attributes
      get :show, {:id => template_wine.to_param}, valid_session
      assigns(:template_wine).should eq(template_wine)
    end
  end

  describe "GET new" do
    it "assigns a new template_wine as @template_wine" do
      get :new, {}, valid_session
      assigns(:template_wine).should be_a_new(TemplateWine)
    end
  end

  describe "GET edit" do
    it "assigns the requested template_wine as @template_wine" do
      template_wine = TemplateWine.create! valid_attributes
      get :edit, {:id => template_wine.to_param}, valid_session
      assigns(:template_wine).should eq(template_wine)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TemplateWine" do
        expect {
          post :create, {:template_wine => valid_attributes}, valid_session
        }.to change(TemplateWine, :count).by(1)
      end

      it "assigns a newly created template_wine as @template_wine" do
        post :create, {:template_wine => valid_attributes}, valid_session
        assigns(:template_wine).should be_a(TemplateWine)
        assigns(:template_wine).should be_persisted
      end

      it "redirects to the created template_wine" do
        post :create, {:template_wine => valid_attributes}, valid_session
        response.should redirect_to(TemplateWine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved template_wine as @template_wine" do
        # Trigger the behavior that occurs when invalid params are submitted
        TemplateWine.any_instance.stub(:save).and_return(false)
        post :create, {:template_wine => {  }}, valid_session
        assigns(:template_wine).should be_a_new(TemplateWine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TemplateWine.any_instance.stub(:save).and_return(false)
        post :create, {:template_wine => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested template_wine" do
        template_wine = TemplateWine.create! valid_attributes
        # Assuming there are no other template_wines in the database, this
        # specifies that the TemplateWine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TemplateWine.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => template_wine.to_param, :template_wine => { "these" => "params" }}, valid_session
      end

      it "assigns the requested template_wine as @template_wine" do
        template_wine = TemplateWine.create! valid_attributes
        put :update, {:id => template_wine.to_param, :template_wine => valid_attributes}, valid_session
        assigns(:template_wine).should eq(template_wine)
      end

      it "redirects to the template_wine" do
        template_wine = TemplateWine.create! valid_attributes
        put :update, {:id => template_wine.to_param, :template_wine => valid_attributes}, valid_session
        response.should redirect_to(template_wine)
      end
    end

    describe "with invalid params" do
      it "assigns the template_wine as @template_wine" do
        template_wine = TemplateWine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TemplateWine.any_instance.stub(:save).and_return(false)
        put :update, {:id => template_wine.to_param, :template_wine => {  }}, valid_session
        assigns(:template_wine).should eq(template_wine)
      end

      it "re-renders the 'edit' template" do
        template_wine = TemplateWine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TemplateWine.any_instance.stub(:save).and_return(false)
        put :update, {:id => template_wine.to_param, :template_wine => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested template_wine" do
      template_wine = TemplateWine.create! valid_attributes
      expect {
        delete :destroy, {:id => template_wine.to_param}, valid_session
      }.to change(TemplateWine, :count).by(-1)
    end

    it "redirects to the template_wines list" do
      template_wine = TemplateWine.create! valid_attributes
      delete :destroy, {:id => template_wine.to_param}, valid_session
      response.should redirect_to(template_wines_url)
    end
  end

end
